version: 2
updates:
  # Enable version updates for npm (nextjs-app)
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the nextjs-app directory
    directory: "/nextjs-app"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit the number of open PRs for version updates
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "alecposner"
    # Labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Always increase the version requirement to match the new version
    versioning-strategy: increase
    # Group all minor and patch updates together
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions" 