version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: bioverse-db
    restart: always
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with your existing PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bioverse_questionnaire
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 