name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'nextjs-app/package-lock.json'

      - name: Install dependencies
        working-directory: ./nextjs-app
        run: npm ci

      - name: Check code formatting
        working-directory: ./nextjs-app
        run: npm run lint --no-fix || echo "Linting issues found but continuing..."

      - name: Build
        working-directory: ./nextjs-app
        env:
          NODE_ENV: production
          # Add dummy environment variables required for the build
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
          JWT_SECRET: dummy_secret_for_build
        run: npm run build

      # Add success message on completion
      - name: Build succeeded
        run: echo "✅ Build passed successfully"

      # Uncomment when you have tests
      # - name: Run tests
      #  working-directory: ./nextjs-app
      #  run: npm test 